In [ ]:
import numpy as np
import pandas as pd
import torch

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/master/data.csv')
df.head()


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Split the data into TRAINING set & TEST set

In [ ]:
X_train, X_test, Y_train, Y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

# Scaling the data because some of the features are in different scales

In [ ]:
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
X_train

array([[-1.80308922,  1.37431364, -1.76962395, ..., -0.95331735,
        -0.16214287,  1.26989129],
       [-0.45528438, -0.52147183, -0.52230964, ..., -1.28174758,
        -1.69059732, -1.36528607],
       [ 2.34328065,  0.07826125,  2.53620728, ...,  2.69759064,
         2.01276701,  0.78443454],
       ...,
       [-1.18165989, -0.46082466, -1.16863774, ..., -0.86424126,
         0.1799971 , -0.55823514],
       [ 0.22160432, -1.03809583,  0.13968203, ..., -0.50566452,
        -0.94614201, -1.24824139],
       [-0.20785027,  0.5050376 , -0.24860947, ..., -0.86030252,
        -0.42519521, -0.96064589]])

In [ ]:
Y_train

539    B
319    B
108    M
250    M
87     M
      ..
440    B
477    B
206    B
511    B
361    B
Name: diagnosis, Length: 455, dtype: object

# Since Y train object is in alphabets, our NN wont understand. Hence we have to use Label encoder

In [ ]:
encoder = LabelEncoder()
Y_train = encoder.fit_transform(Y_train)
Y_test = encoder.transform(Y_test)

In [ ]:
Y_train

array([0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,

# For our NN, we need tensors. Hence we will convert numpy arrays to tensors

In [ ]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
Y_train_tensor=torch.from_numpy(Y_train)
Y_test_tensor=torch.from_numpy(Y_test)

In [ ]:
X_train_tensor

tensor([[-1.8031,  1.3743, -1.7696,  ..., -0.9533, -0.1621,  1.2699],
        [-0.4553, -0.5215, -0.5223,  ..., -1.2817, -1.6906, -1.3653],
        [ 2.3433,  0.0783,  2.5362,  ...,  2.6976,  2.0128,  0.7844],
        ...,
        [-1.1817, -0.4608, -1.1686,  ..., -0.8642,  0.1800, -0.5582],
        [ 0.2216, -1.0381,  0.1397,  ..., -0.5057, -0.9461, -1.2482],
        [-0.2079,  0.5050, -0.2486,  ..., -0.8603, -0.4252, -0.9606]],
       dtype=torch.float64)

# Create a model

In [ ]:
class MySimpleModel:
    def __init__(self, X):
      self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
      self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

    def forward(self, X):
      z=torch.matmul(X, self.weights) + self.bias  # z = wx + b
      y_pred = torch.sigmoid(z)                    # y_pred = sigmoid(z)
      return y_pred

    def loss_function(self, y_pred, y):
      epsilon=1e-7
      y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

      # Calculate loss
      loss = -(Y_train_tensor * torch.log(y_pred) + (1 - Y_train_tensor) * torch.log(1 - y_pred)).mean()
      return loss

In [ ]:
learning_rate=0.1
epochs = 25

In [ ]:
# Now we need to train the model
# a) Create the model instance
model=MySimpleModel(X_train_tensor)

for epoch in range(epochs):
  # b) Forward pass
  y_pred=model.forward(X_train_tensor)

  # c) loss calculation
  loss=model.loss_function(y_pred,Y_train_tensor)

  # d) back propagation
  loss.backward()

  # e) parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # f) zero the gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.583981934450978
Epoch: 2, Loss: 3.4613429255786965
Epoch: 3, Loss: 3.337088728586941
Epoch: 4, Loss: 3.2058592804043573
Epoch: 5, Loss: 3.065881841747957
Epoch: 6, Loss: 2.9212684206278325
Epoch: 7, Loss: 2.7716631294784513
Epoch: 8, Loss: 2.614865109226233
Epoch: 9, Loss: 2.4552986330423066
Epoch: 10, Loss: 2.2946509788006724
Epoch: 11, Loss: 2.123651974621273
Epoch: 12, Loss: 1.9550611209175681
Epoch: 13, Loss: 1.7930169028826068
Epoch: 14, Loss: 1.6335258429657358
Epoch: 15, Loss: 1.479489134458466
Epoch: 16, Loss: 1.334909183518141
Epoch: 17, Loss: 1.2051971235359065
Epoch: 18, Loss: 1.0889530647720556
Epoch: 19, Loss: 0.9928185600013856
Epoch: 20, Loss: 0.9173590363801891
Epoch: 21, Loss: 0.8612649765888537
Epoch: 22, Loss: 0.8214581384509152
Epoch: 23, Loss: 0.7940088474116626
Epoch: 24, Loss: 0.7751825797900197
Epoch: 25, Loss: 0.7620262851872455


In [ ]:
model.bias

tensor([-0.1299], dtype=torch.float64, requires_grad=True)

# Evaluation

In [ ]:
from itertools import accumulate
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == Y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5215451121330261
