In [6]:
import torch
import numpy as np

In [7]:
def onehot_encoder(position,depth):
    onehot=torch.zeros((depth,))
    onehot[position]=1
    return onehot

def int_to_onehot(number):
  onehot=onehot_encoder(number, 100)
  return onehot

In [4]:
# Function to generate 10 ints (between 0 & 99) that are multiple of 5
def gen_sequence():
    indices = torch.randint(0, 20, (10,))
    sequence = indices*5
    return sequence

sequence = gen_sequence()
print(sequence)

tensor([80, 65, 60, 15, 95, 15, 40, 75, 65, 20])


In [9]:
# Convert each int in preceding step into one-hot var
def gen_batch():
  sequence = gen_sequence()
  batch=[int_to_onehot(i).numpy() for i in sequence]
  batch=np.array(batch)
  return torch.tensor(batch)

batch=gen_batch()
print(batch)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         

In [10]:
def data_to_num(data):
    num=torch.argmax(data,dim=-1)
    return num
numbers=data_to_num(batch)
print(numbers)

tensor([25, 10, 35, 90, 30, 65, 25, 30, 10, 65])
