In [1]:
import torch
import numpy as np

In [2]:
def onehot_encoder(position,depth):
    onehot=torch.zeros((depth,))
    onehot[position]=1
    return onehot

def int_to_onehot(number):
  onehot=onehot_encoder(number, 100)
  return onehot

In [3]:
# Function to generate 10 ints (between 0 & 99) that are multiple of 5
def gen_sequence():
    indices = torch.randint(0, 20, (10,))
    sequence = indices*5
    return sequence

sequence = gen_sequence()
print(sequence)

tensor([95, 55, 80, 40, 40, 70, 50, 70, 90, 65])


In [4]:
# Convert each int in preceding step into one-hot var
def gen_batch():
  sequence = gen_sequence()
  batch=[int_to_onehot(i).numpy() for i in sequence]
  batch=np.array(batch)
  return torch.tensor(batch)

batch=gen_batch()
print(batch)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         

In [5]:
def data_to_num(data):
    num=torch.argmax(data,dim=-1)
    return num
numbers=data_to_num(batch)
print(numbers)

tensor([75, 15, 80, 75, 85, 80, 20, 70, 90,  5])


In [7]:
from torch import nn

device="cuda" if torch.cuda.is_available() else "cpu"

# Discriminator
D=nn.Sequential(
    nn.Linear(100,1),
    nn.Sigmoid()).to(device)

In [8]:
# Generator

G=nn.Sequential(
    nn.Linear(100,100),
    nn.ReLU()).to(device)


In [9]:
loss_fn=nn.BCELoss()
lr=0.0005
optimD=torch.optim.Adam(D.parameters(),lr=lr)
optimG=torch.optim.Adam(G.parameters(),lr=lr)